Repository TheAsel/BYBE-frontend, pull requests merged in 2024-10, with the labels that each got.

#47 ✨ Misc improvements
  .env
  .eslintignore
  .eslintrc.cjs
  .gitignore
  Dockerfile
  README.md
  nginx.conf
  package-lock.json
  package.json
  postcss.config.js
  quasar.config.ts
  src/boot/globals.ts
  src/components/Encounter/CreatureList.vue
  src/components/Encounter/CreaturesTable.vue
  src/components/Encounter/CreaturesTable/EncounterBuilder.vue
  src/components/Encounter/CreaturesTable/PartyBuilder.vue
  src/components/HeaderBar.vue
  src/components/Shop/ShopList.vue
  src/components/Shop/ShopSheet.vue
  src/components/Shop/ShopSheet/ArmorSheet.vue
  src/components/Shop/ShopSheet/ItemSheet.vue
  src/components/Shop/ShopSheet/ShieldSheet.vue
  src/components/Shop/ShopSheet/WeaponSheet.vue
  src/components/Shop/ShopTable.vue
  src/components/Shop/ShopTable/ShopBuilder.vue
  src/layouts/MainLayout.vue
  src/pages/BestiaryPage.vue
  src/pages/EncounterPage.vue
  src/pages/ErrorNotFound.vue
  src/pages/IndexPage.vue
  src/pages/ItemPage.vue
  src/pages/LicensePage.vue
  src/pages/NpcPage.vue
  src/pages/ShopPage.vue
  src/stores/store-flag.d.ts
  src/types/filters.ts
  src/utils/encounter-api-calls.ts
  src/utils/shop-api-calls.ts
  tsconfig.json
  tsconfig.vue-tsc.json
Labels: enhancement

#48 ✨ Custom shop templates
  package-lock.json
  package.json
  src/components/Encounter/CreatureList.vue
  src/components/Encounter/CreaturesTable.vue
  src/components/Encounter/CreaturesTable/EncounterBuilder.vue
  src/components/Encounter/CreaturesTable/PartyBuilder.vue
  src/components/HeaderBar.vue
  src/components/Shop/ShopList.vue
  src/components/Shop/ShopTable.vue
  src/components/Shop/ShopTable/ShopBuilder.vue
  src/pages/EncounterPage.vue
  src/pages/ShopPage.vue
  src/stores/store.ts
  src/types/item.ts
  src/types/template.ts
  src/utils/shop-api-calls.ts
Labels: enhancement, shop

#49 🔧 Switched to .env for auto-open of browser
  .env
  package-lock.json
  package.json
  quasar.config.ts
Labels: enhancement

#52 🐛 Fix shop layout shift, cart col no more default
  src/components/Shop/ShopTable.vue
  src/components/Shop/SkeletonTable.vue
  src/pages/EncounterPage.vue
  src/pages/ShopPage.vue
Labels: bug

#51 🎨 Remove Ko-Fi widget from DOM when hidden
  index.html
  src/components/HeaderBar.vue
  src/pages/ErrorNotFound.vue
Labels: enhancement

#50 💄 UI tweaks
  .env
  package-lock.json
  package.json
  public/dice/d10.png
  public/dice/d10.webp
  public/dice/d12.png
  public/dice/d12.webp
  public/dice/d20.png
  public/dice/d20.webp
  public/dice/d4.png
  public/dice/d4.webp
  public/dice/d6.png
  public/dice/d6.webp
  public/dice/d8.png
  public/dice/d8.webp
  quasar.config.ts
  src/components/Encounter/CreatureList.vue
  src/components/Encounter/CreaturesTable/EncounterBuilder.vue
  src/components/HeaderBar.vue
  src/components/Shop/ShopTable/ShopBuilder.vue
  src/css/app.scss
  src/css/fonts/Bold/OpenSans-Bold.woff2
  src/css/fonts/Bold/open-sans-700.woff2
  src/css/fonts/BoldItalic/OpenSans-BoldItalic.woff2
  src/css/fonts/BoldItalic/open-sans-italic-700.woff2
  src/css/fonts/Italic/OpenSans-Italic.woff2
  src/css/fonts/Medium/open-sans-500.woff2
  src/css/fonts/MediumItalic/open-sans-italic-500.woff2
  src/css/fonts/Regular/OpenSans-Regular.woff2
  src/layouts/MainLayout.vue
  src/pages/EncounterPage.vue
  src/pages/IndexPage.vue
  src/pages/ShopPage.vue
  src/types/github.ts
  src/utils/github-api.ts
Labels: enhancement
